import type { AdminProductFormValues } from "@/types/product-admin";

const fieldClass = "mt-2 h-12 w-full rounded-xl border border-[#d8e0e8] bg-white px-4 text-sm text-[#07172b] outline-none transition focus:border-[#e52833] focus:ring-4 focus:ring-[#e52833]/10";
const textareaClass = `${fieldClass} h-auto resize-y py-3 leading-6`;
const labelClass = "block text-[10px] font-black uppercase tracking-[0.11em] text-[#4c5b70]";

interface ProductFormProps {
  action: (formData: FormData) => void | Promise<void>;
  product?: AdminProductFormValues;
  canPublish: boolean;
}

export function ProductForm({ action, product, canPublish }: ProductFormProps) {
  return (
    <form action={action} className="mt-8 space-y-6" encType="multipart/form-data">
      <section className="rounded-[22px] border border-[#e0e6ed] bg-white p-6 shadow-[0_8px_28px_rgba(7,23,43,0.04)] sm:p-8"><div className="border-b border-[#e9edf2] pb-5"><h2 className="text-lg font-black text-[#07172b]">Basic product information</h2><p className="mt-1 text-xs text-[#748196]">Core catalogue identity and publication details.</p></div><div className="mt-6 grid gap-5 md:grid-cols-2"><label className={labelClass}>Product name<input required name="name" defaultValue={product?.name} className={fieldClass} maxLength={160} /></label><label className={labelClass}>Mutsimoto part number<input required name="partNumber" defaultValue={product?.partNumber} className={fieldClass} maxLength={100} /></label><label className={labelClass}>Canonical slug<input required name="slug" defaultValue={product?.slug} className={fieldClass} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="mf-101-oil-filter" /></label><label className={labelClass}>Availability<input required name="availability" defaultValue={product?.availability ?? "In stock"} className={fieldClass} /></label><label className={labelClass}>Category<select name="category" defaultValue={product?.category ?? "oil"} className={fieldClass}><option value="oil">Oil filter</option><option value="fuel">Fuel filter</option><option value="air">Air filter</option></select></label><label className={labelClass}>Application type<select name="applicationType" defaultValue={product?.applicationType ?? "automotive"} className={fieldClass}><option value="automotive">Automotive</option><option value="industrial">Industrial</option><option value="both">Automotive and industrial</option></select></label></div><label className={`${labelClass} mt-5`}>Short description<textarea required name="shortDescription" defaultValue={product?.shortDescription} rows={3} className={textareaClass} maxLength={320} /></label><label className={`${labelClass} mt-5`}>Full description<textarea required name="fullDescription" defaultValue={product?.fullDescription} rows={7} className={textareaClass} maxLength={5000} /></label><label className="mt-5 flex items-center gap-3 text-sm font-bold text-[#344358]"><input name="featured" type="checkbox" defaultChecked={product?.featured} className="size-4 accent-[#e52833]" />Feature this product on the public homepage</label></section>
      <section className="rounded-[22px] border border-[#e0e6ed] bg-white p-6 shadow-[0_8px_28px_rgba(7,23,43,0.04)] sm:p-8"><div className="border-b border-[#e9edf2] pb-5"><h2 className="text-lg font-black text-[#07172b]">Product image</h2><p className="mt-1 text-xs text-[#748196]">JPEG, PNG or WebP. Maximum 5 MB. A new upload becomes the primary image.</p></div>{product?.primaryImagePath && <p className="mt-5 rounded-xl bg-[#f3f6f9] px-4 py-3 font-mono text-xs text-[#59687c]">Current: {product.primaryImagePath}</p>}<div className="mt-5 grid gap-5 md:grid-cols-2"><label className={labelClass}>Primary image<input name="primaryImage" type="file" accept="image/jpeg,image/png,image/webp" className={`${fieldClass} h-auto py-3 file:mr-4 file:rounded-full file:border-0 file:bg-[#07172b] file:px-4 file:py-2 file:text-xs file:font-bold file:text-white`} /></label><label className={labelClass}>Accessible alt text<input name="imageAlt" defaultValue={product?.imageAlt} className={fieldClass} placeholder="Front view of MF-101 oil filter" /></label></div></section>
      <section className="rounded-[22px] border border-[#e0e6ed] bg-white p-6 shadow-[0_8px_28px_rgba(7,23,43,0.04)] sm:p-8"><div className="border-b border-[#e9edf2] pb-5"><h2 className="text-lg font-black text-[#07172b]">Technical data and references</h2><p className="mt-1 text-xs text-[#748196]">Enter one structured record per line using the examples shown.</p></div><div className="mt-6 grid gap-5 xl:grid-cols-2"><label className={labelClass}>Specifications<textarea name="specifications" defaultValue={product?.specifications} rows={8} className={textareaClass} placeholder={"Height | 105 | mm\nFilter media | Synthetic cellulose |"} /><span className="mt-2 block normal-case tracking-normal text-[11px] font-medium text-[#8490a1]">Label | Value | Optional unit</span></label><label className={labelClass}>Cross references<textarea name="references" defaultValue={product?.references} rows={8} className={textareaClass} placeholder={"oem | Toyota | 90915-YZZD2\ncompetitor | Fleetguard | LF1234"} /><span className="mt-2 block normal-case tracking-normal text-[11px] font-medium text-[#8490a1]">Type | Manufacturer | Reference number</span></label></div></section>
      <section className="rounded-[22px] border border-[#e0e6ed] bg-white p-6 shadow-[0_8px_28px_rgba(7,23,43,0.04)] sm:p-8"><div className="border-b border-[#e9edf2] pb-5"><h2 className="text-lg font-black text-[#07172b]">Applications</h2><p className="mt-1 text-xs text-[#748196]">Structured fitment records power public search and product compatibility details.</p></div><div className="mt-6 grid gap-5 xl:grid-cols-2"><label className={labelClass}>Vehicle applications<textarea name="vehicleApplications" defaultValue={product?.vehicleApplications} rows={8} className={textareaClass} placeholder="Toyota | Hilux | 1KD-FTV | 2005 | 2015 | Diesel models" /><span className="mt-2 block normal-case tracking-normal text-[11px] font-medium text-[#8490a1]">Brand | Model | Engine | From | To | Notes</span></label><label className={labelClass}>Equipment applications<textarea name="equipmentApplications" defaultValue={product?.equipmentApplications} rows={8} className={textareaClass} placeholder="Generator | Power generation | Cummins | C150D5 | 6BT5.9 | Primary filter" /><span className="mt-2 block normal-case tracking-normal text-[11px] font-medium text-[#8490a1]">Type | Industry | Manufacturer | Model | Engine | Notes</span></label></div></section>
      <section className="rounded-[22px] border border-[#e0e6ed] bg-white p-6 shadow-[0_8px_28px_rgba(7,23,43,0.04)] sm:p-8"><div className="border-b border-[#e9edf2] pb-5"><h2 className="text-lg font-black text-[#07172b]">Search and social metadata</h2><p className="mt-1 text-xs text-[#748196]">Optional copy for search results and product link previews.</p></div><div className="mt-6 grid gap-5 md:grid-cols-2"><label className={labelClass}>SEO title<input name="seoTitle" defaultValue={product?.seoTitle} className={fieldClass} maxLength={160} /></label><label className={labelClass}>SEO description<textarea name="seoDescription" defaultValue={product?.seoDescription} rows={3} className={textareaClass} maxLength={320} /></label></div></section>
      <div className="sticky bottom-4 z-10 flex flex-wrap items-center justify-end gap-2 rounded-2xl border border-[#d9e1e9] bg-white/95 p-4 shadow-[0_16px_50px_rgba(7,23,43,0.15)] backdrop-blur-xl"><button type="submit" name="intent" value="draft" className="inline-flex min-h-11 items-center justify-center rounded-full border border-[#d5dde6] px-5 text-sm font-black text-[#07172b] hover:bg-[#f2f5f8]">Save draft</button><button type="submit" name="intent" value="review" className="inline-flex min-h-11 items-center justify-center rounded-full bg-[#e8b449] px-5 text-sm font-black text-[#3e2c07] hover:bg-[#dcaa3f]">Submit for review</button>{canPublish && <button type="submit" name="intent" value="publish" className="button-primary">Publish product</button>}</div>
    </form>
  );
}

